doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    WebburzaSyliusWishlistPlugin:
                        type: xml
                        prefix: Webburza\SyliusWishlistPlugin\Model
                        dir: 'Resources/config/doctrine'
                        is_bundle: true
                        mapping: true
        resolve_target_entities:
            Sylius\Component\Core\Model\ShopUserInterface: Sylius\Component\Core\Model\ShopUser

twig:
    globals:
        wishlist_provider: '@webburza_sylius_wishlist.provider.wishlist'
